---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/ejba/pre-commit-maven
    rev: v0.3.4
    hooks:
      - id: maven-spotless-apply
  - repo: local
    hooks:
      - id: git-config-blame-ignore-revs
        name: configure git-blame ignoreRevsFile
        entry: git config --local --replace-all blame.ignoreRevsFile .git-blame-ignore-revs
        language: system
